#!/usr/bin/env bash
# usage: stemconv dicname(without aff, dic extension)
cat $1.aff | sed '
	s#[&]agrave;##;
	s# [&(]$##;
        ' >$1.aff$$ && mv $1.aff$$ $1.aff
cat $1.dic | sed ' s#/[&(]	#	#' >$1.dic$$ && mv $1.dic$$ $1.dic
