#!/usr/bin/env bash
# hasonló szavak kiszûrésére
# Németh László <nemeth@gyorsposta.hu>
# Usage: simwords < file
awk '
BEGIN { prev = ""}
{
    if (length(prev) == length($1)) {
	i = 1;
	n = 0;
	pos = 0;
	len = length($1);
	while ((i <= len) && (n < 2)) {
		if ((substr(prev, i, 1) != substr($1, i, 1))) {
		    n++;
		    if (n == 1) pos = i;
		}
		i++;
	}
	i1 = index("aáeéiíoóöõuúüû",substr(prev, pos, 1));
	i2 = index("aáeéiíoóöõuúüû",substr($1, pos, 1));
	if ((n == 1) && (i1 != 0) && (i2 != 0) && ((i1-i2) * (i1-i2) == 1)) {
	    print prev " " $1;
	}
    }
    prev = $1;
}'
