#!/bin/sh
# szavak tördelése a ChangeLog állományhoz
sed 's/^\s*//g' | tr '\n' ' ' | tr ',' '\n' | sed 's/^ *//' | sort | uniq  | sed 's/ *//' | awk '{print $0","}' | tr '\n' ' ' | fmt -w 70 | awk '{print "\t  "$0}'
